quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=devuser
quarkus.datasource.password=devpassword
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/dev_db
quarkus.hibernate-orm.database.generation=update
kafka.bootstrap.servers=kafka:9092
quarkus.http.host=0.0.0.0
