quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.enabled=false
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
# Reactive URL (kept for reactive clients if needed)
quarkus.datasource.reactive.url=postgresql://localhost:5432/seats_db
# JDBC URL required by Hibernate ORM
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/seats_db
quarkus.datasource.jdbc.max-size=16

# HTTP server
quarkus.http.host=0.0.0.0
quarkus.http.port=8080

quarkus.smallrye-graphql.ui.always-include=true
quarkus.smallrye-graphql.root-path=/api/graphql
quarkus.smallrye-graphql.show-runtime-exception-message=io.quarkus.security.UnauthorizedException,io.quarkus.security.ForbiddenException
quarkus.smallrye-graphql.error-extension-fields=exception,classification,code,description,validationErrorType,queryPath

# CORS for UI dev server
#quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173,http://127.0.0.1:5173,http://192.168.1.19:3001,http://Localhost:3001
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.exposed-headers=location
quarkus.http.cors.access-control-max-age=86400
quarkus.http.cors.enabled=true
quarkus.http.cors.access-control-allow-credentials=true
# This specifically fixes the "local address space" block
quarkus.http.cors.access-control-allow-private-network=true